FROM node:latest
RUN mkdir /frontend
WORKDIR /frontend
COPY . /frontend/
COPY package.json /frontend/
COPY package-lock.json /frontend/
RUN rm -rIf node_modules
RUN npm install --save-dev webpack
RUN npm install webpack-cli
RUN yarn build