  version: '3.1'
    
  services:
  
  #Django Web Server with Application backend
    django:
      build: 
        context: .
        dockerfile: Dockerfile_django
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - "mongo"

  #NPM server for react
    #react:
    #  build:
    #    context: frontend
    #    dockerfile: Dockerfile_react
    #  command: npm run dev
    #  volumes:
    #    - .:/frontend

  #mongodb container
    mongo:
      image: mongo
      restart: always
      ports:
        - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: gokulnune
        MONGO_INITDB_ROOT_PASSWORD: example
    
    #Web-based MongoDB admin interface, written with Node.js and express
    mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: gokulnune
        ME_CONFIG_MONGODB_ADMINPASSWORD: example


#
#    pgadmin:
#      image: dpage/pgadmin4
#      container_name: demo-pgadmin #you can change this
#      depends_on:
#       - db
#      ports:
#        - "5051:80"
#      environment:
#        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
#        PGADMIN_DEFAULT_PASSWORD: root
#      restart: always