FROM python:3
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE djangopsqlcontainer.settings
RUN pip install --upgrade pip
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip3 install -r requirements.txt
COPY djangopsqlcontainer /code/
COPY mydeck /code/
COPY manage.py /code/