# Generated by Django 2.2.15 on 2020-08-04 07:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydeck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_id', models.CharField(default='new_deck', max_length=20)),
                ('deck_cards', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='card',
            name='question_text',
        ),
        migrations.AddField(
            model_name='card',
            name='card_content',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=800), blank=True, default=list, size=10),
        ),
        migrations.AddField(
            model_name='card',
            name='card_id',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(default='flash', max_length=10),
        ),
    ]
