# Generated by Django 3.0.8 on 2020-08-03 04:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydeck', '0002_auto_20200803_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_content',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=800), default=[0, 'Card Content Goes Here'], null=True, size=10),
        ),
        migrations.AlterField(
            model_name='deck',
            name='deck_cards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=[0, '0000000000'], null=True, size=10),
        ),
    ]
