# Generated by Django 2.2.15 on 2020-09-07 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydeck', '0002_auto_20200804_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydeck.Deck'),
        ),
    ]
