# Generated by Django 3.1 on 2020-09-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydeck', '0002_auto_20200912_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_content',
        ),
        migrations.RemoveField(
            model_name='card',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='creator',
        ),
        migrations.AddField(
            model_name='card',
            name='card_answer',
            field=models.CharField(default='Pedegogy', max_length=100),
        ),
        migrations.AddField(
            model_name='card',
            name='card_question',
            field=models.CharField(default='The Study of Learning', max_length=100),
        ),
        migrations.RemoveField(
            model_name='deck',
            name='cards_deck',
        ),
        migrations.AddField(
            model_name='deck',
            name='cards_deck',
            field=models.ManyToManyField(to='mydeck.Card'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='deck_name',
            field=models.CharField(default='New Deck', max_length=20),
        ),
    ]
