# Generated by Django 3.1 on 2020-09-16 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydeck', '0003_auto_20200914_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='cards_deck',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='deck_id',
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mydeck.deck'),
        ),
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='deck',
            name='slug',
            field=models.CharField(default='', max_length=64),
        ),
    ]
