# Generated by Django 2.2.15 on 2020-09-07 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydeck', '0003_card_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydeck.Deck'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='deck_id',
            field=models.CharField(max_length=20),
        ),
    ]
