# Generated by Django 3.1 on 2020-09-18 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mydeck', '0004_auto_20200918_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
