# Generated by Django 2.2.15 on 2020-09-07 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydeck', '0004_auto_20200907_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydeck.Deck'),
        ),
    ]
