# Generated by Django 3.0.8 on 2020-08-03 04:33

import django.contrib.postgres.fields
from django.db import migrations, models
import mydeck.models


class Migration(migrations.Migration):

    dependencies = [
        ('mydeck', '0005_auto_20200803_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_content',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=800), default=mydeck.models.get_default_card, null=True, size=10),
        ),
    ]
