# Generated by Django 2.2.15 on 2020-09-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydeck', '0005_auto_20200907_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='deck_id',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
