# Generated by Django 3.1 on 2020-09-16 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(default='New Deck', max_length=20)),
                ('slug', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(default='flash', max_length=10)),
                ('card_question', models.CharField(default='The Study of Learning', max_length=100)),
                ('card_answer', models.CharField(default='Pedegogy', max_length=100)),
                ('slug', models.CharField(default='', max_length=64)),
                ('deck', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mydeck.deck')),
            ],
        ),
    ]
