# Generated by Django 3.1 on 2020-09-16 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydeck', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='deck',
            new_name='deck_id',
        ),
    ]
