# Generated by Django 3.1 on 2020-09-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydeck', '0002_auto_20200916_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='uid',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='deck',
            name='uid',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='deck',
            name='deck_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
